/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.factura;
import ec.edu.ups.controladores.ControladorFacturaDetalle;
import ec.edu.ups.controladores.ControladorProducto;
import ec.edu.ups.modelo.FacturaDetalle;
import ec.edu.ups.modelo.Producto;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.JOptionPane;
public class VentanaFacturaDetalle extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaFacturaDetalle
     */
    private ControladorProducto controladorProducto;
    private ControladorFacturaDetalle controladorFacturaDetalle;
    private Set<Producto> lista;
    double subTotal;
    int indice = 0;
    private Locale localizacion;
    private static ResourceBundle mensajes;
    
    public VentanaFacturaDetalle(ControladorFacturaDetalle controladorFacturaDetalle, ControladorProducto controladorProducto) {
        initComponents();
        this.controladorFacturaDetalle= controladorFacturaDetalle;
        this.controladorProducto = controladorProducto;
        FCodigo.setText(String.valueOf(this.controladorFacturaDetalle.getCodigo()));
        lista = controladorProducto.getLista();
        for(Producto producto: lista){
            buscar.addItem(producto.getNombre());
        }
    productoBuscado();
    }
    public static void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        codigo.setText(mensajes.getString("cliente.codigo"));
        producto.setText(mensajes.getString("menu.producto"));
        Punitario.setText(mensajes.getString("precio.uni"));
        cantidad.setText(mensajes.getString("cantidad"));
        subtotal.setText(mensajes.getString("subtotal"));
        anadirpro.setText(mensajes.getString("anadir"));
    }
    
    public void productoBuscado(){
        Producto producto = buscarProducto();
        PUnitario.setText(String.valueOf(producto.getPrecio()));
    }
    
    public Producto buscarProducto(){
        Producto l = new Producto();
        for(Producto producto : lista){
        if(buscar.getSelectedItem().toString().equalsIgnoreCase(producto.getNombre())){    
        l = producto;
        }
    }
           return l;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        FCodigo = new javax.swing.JTextField();
        producto = new javax.swing.JLabel();
        FCantidad = new javax.swing.JTextField();
        cantidad = new javax.swing.JLabel();
        FSubtotal = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        Punitario = new javax.swing.JLabel();
        PUnitario = new javax.swing.JTextField();
        anadirpro = new javax.swing.JLabel();
        buscar = new javax.swing.JComboBox<>();
        Añadir = new javax.swing.JButton();
        Calcular = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        codigo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo.setText("CODIGO");

        FCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FCodigo.setEnabled(false);

        producto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        producto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producto.setText("PRODUCTO");

        FCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidad.setText("CANTIDAD");

        FSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FSubtotal.setEnabled(false);

        subtotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotal.setText("SUBTOTAL");

        Punitario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Punitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Punitario.setText("P. UNITARIO");

        PUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PUnitario.setEnabled(false);

        anadirpro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        anadirpro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirpro.setText("AÑADIR PRODUCTO");

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/crear.png"))); // NOI18N
        Añadir.setToolTipText("");
        Añadir.setActionCommand("Añadir Producto");
        Añadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/CALCULAR.png"))); // NOI18N
        Calcular.setToolTipText("");
        Calcular.setActionCommand("Calcular Sub Total");
        Calcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Punitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PUnitario)
                            .addComponent(FCantidad)
                            .addComponent(FSubtotal)
                            .addComponent(buscar, 0, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(anadirpro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Punitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(subtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anadirpro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Añadir.getAccessibleContext().setAccessibleName("Añadir Producto");
        Calcular.getAccessibleContext().setAccessibleName("Calcular Sub Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        Producto producto = buscarProducto();
        FacturaDetalle facDetalle = new FacturaDetalle();
        facDetalle.setPrecio(Double.parseDouble(PUnitario.getText()));
        facDetalle.setCantidad(Integer.parseInt(FCantidad.getText()));
        facDetalle.setSubtotal(Double.parseDouble(FSubtotal.getText()));
        facDetalle.setProducto(producto);
        facDetalle.setCodfac(VentanaFactura.codigoFac);
        controladorFacturaDetalle.crear(facDetalle);
        Object[] fila = {facDetalle.getCodigo(),
                         producto.getNombre(),
                         facDetalle.getPrecio(),
                         facDetalle.getCantidad(),
                         facDetalle.getSubtotal()};
        VentanaFactura.Tabla.addRow(fila);
        JOptionPane.showMessageDialog(this, "Producto Ingresado");
        FCodigo.setText(String.valueOf(this.controladorFacturaDetalle.getCodigo()));
        FCantidad.setText("");
        FSubtotal.setText("");
        Añadir.setEnabled(false);
    }//GEN-LAST:event_AñadirActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        if(PUnitario.getText().isEmpty()){            
        }else if(FCantidad.getText().isEmpty()){
        }else{
        subTotal = (Double.parseDouble(PUnitario.getText()))*(Double.parseDouble(FCantidad.getText()));
        FSubtotal.setText(String.valueOf(subTotal));
        Añadir.setEnabled(true);
        }        
    }//GEN-LAST:event_CalcularActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        buscarProducto();
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Añadir;
    public static javax.swing.JButton Calcular;
    private javax.swing.JTextField FCantidad;
    private javax.swing.JTextField FCodigo;
    private javax.swing.JTextField FSubtotal;
    private javax.swing.JTextField PUnitario;
    public static javax.swing.JLabel Punitario;
    public static javax.swing.JLabel anadirpro;
    private javax.swing.JComboBox<String> buscar;
    public static javax.swing.JLabel cantidad;
    public static javax.swing.JLabel codigo;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel producto;
    public static javax.swing.JLabel subtotal;
    // End of variables declaration//GEN-END:variables
}
