/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.cliente;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

public class VentanaActualizarCliente extends javax.swing.JInternalFrame {

    private ControladorCliente controladorCliente;
    private Locale localizacion;
    private static ResourceBundle mensajes;

    public VentanaActualizarCliente(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente = controladorCliente;
    }

    public static void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes",Locale.getDefault());
        ACcodigo.setText(mensajes.getString("cliente.codigo"));
        ACnombre.setText(mensajes.getString("cliente.nombre"));
        ACapellido.setText(mensajes.getString("cliente.apellido"));
        ACcedula.setText(mensajes.getString("cliente.cedula"));
        ACdireccion.setText(mensajes.getString("cliente.direccion"));
        ACtelefono.setText(mensajes.getString("cliente.telefono"));
        ACactualizar.setText(mensajes.getString("boton.actualizar"));
        ACbuscar.setText(mensajes.getString("boton.buscar"));
        ACcancelar.setText(mensajes.getString("boton.cancelar"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACcodigo = new javax.swing.JLabel();
        ACcedula = new javax.swing.JLabel();
        Acodigo = new javax.swing.JTextField();
        ACnombre = new javax.swing.JLabel();
        Acedula = new javax.swing.JTextField();
        Anombre = new javax.swing.JTextField();
        ACdireccion = new javax.swing.JLabel();
        Adireccion = new javax.swing.JTextField();
        Atelefono = new javax.swing.JTextField();
        ACtelefono = new javax.swing.JLabel();
        ACbuscar = new javax.swing.JButton();
        ACcancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ACactualizar = new javax.swing.JButton();
        Aapellido = new javax.swing.JTextField();
        ACapellido = new javax.swing.JLabel();

        setClosable(true);

        ACcodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACcodigo.setText("CODIGO");

        ACcedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACcedula.setText("CEDULA");

        Acodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcodigoActionPerformed(evt);
            }
        });

        ACnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACnombre.setText("NOMBRE");

        ACdireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACdireccion.setText("DIRECCION");
        ACdireccion.setToolTipText("");

        ACtelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACtelefono.setText("TELEFONO");

        ACbuscar.setText("BUSCAR");
        ACbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACbuscarActionPerformed(evt);
            }
        });

        ACcancelar.setText("CANCELAR");
        ACcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACcancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTUALIZAR CLIENTE");

        ACactualizar.setText("ACTUALIZAR");
        ACactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACactualizarActionPerformed(evt);
            }
        });

        ACapellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACapellido.setText("APELLIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ACcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Acodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ACnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ACcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ACapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Anombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Acedula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Aapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ACbuscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ACactualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACcancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ACdireccion)
                                .addComponent(ACtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Adireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Atelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACbuscar))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACcedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACnombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACapellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACdireccion)
                    .addComponent(Adireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACtelefono)
                    .addComponent(Atelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACcancelar)
                    .addComponent(ACactualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcodigoActionPerformed

    private void ACbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACbuscarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(Acodigo.getText());
        Cliente buscarCliente = controladorCliente.read(codigo);
        Acedula.setText(buscarCliente.getCedula());
        Anombre.setText(buscarCliente.getNombre());
        Aapellido.setText(buscarCliente.getApellido());
        Adireccion.setText(buscarCliente.getDireccion());
        Atelefono.setText(buscarCliente.getTelefono());
    }//GEN-LAST:event_ACbuscarActionPerformed

    private void ACcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ACcancelarActionPerformed

    private void ACactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACactualizarActionPerformed
        // TODO add your handling code here:
        Cliente actualizarCliente = new Cliente();
        actualizarCliente.setCodigo(Integer.parseInt(Acodigo.getText()));
        actualizarCliente.setCedula(Acedula.getText());
        actualizarCliente.setNombre(Anombre.getText());
        actualizarCliente.setApellido(Aapellido.getText());
        actualizarCliente.setDireccion(Adireccion.getText());
        actualizarCliente.setTelefono(Atelefono.getText());
        controladorCliente.update(actualizarCliente);
        JOptionPane.showMessageDialog(this, "CLIENTE ACTUALIZADO");
        Acodigo.setText("");
        Acedula.setText("");
        Anombre.setText("");
        Aapellido.setText("");
        Adireccion.setText("");
        Atelefono.setText("");
    }//GEN-LAST:event_ACactualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ACactualizar;
    public static javax.swing.JLabel ACapellido;
    public static javax.swing.JButton ACbuscar;
    public static javax.swing.JButton ACcancelar;
    public static javax.swing.JLabel ACcedula;
    public static javax.swing.JLabel ACcodigo;
    public static javax.swing.JLabel ACdireccion;
    public static javax.swing.JLabel ACnombre;
    public static javax.swing.JLabel ACtelefono;
    private javax.swing.JTextField Aapellido;
    private javax.swing.JTextField Acedula;
    private javax.swing.JTextField Acodigo;
    private javax.swing.JTextField Adireccion;
    private javax.swing.JTextField Anombre;
    private javax.swing.JTextField Atelefono;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
