package ec.edu.ups.vista.cliente;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import javax.swing.JOptionPane;
import java.util.Locale;
import java.util.ResourceBundle;

public class VentanaEliminarCliente extends javax.swing.JInternalFrame {

    private Locale localizacion;
    private static ResourceBundle mensajes;
    private ControladorCliente controladorCliente;

    public VentanaEliminarCliente(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente = controladorCliente;
    }

    public static void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        ECcodigo.setText(mensajes.getString("cliente.codigo"));
        ECnombre.setText(mensajes.getString("cliente.nombre"));
        ECapellido.setText(mensajes.getString("cliente.apellido"));
        ECcedula.setText(mensajes.getString("cliente.cedula"));
        ECdireccion.setText(mensajes.getString("cliente.direccion"));
        ECtelefono.setText(mensajes.getString("cliente.telefono"));
        Beliminar.setText(mensajes.getString("boton.eliminar"));
        Bcancelar.setText(mensajes.getString("boton.cancelar"));
        Bbuscar.setText(mensajes.getString("boton.buscar"));
        MEC.setText(mensajes.getString("MCC"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bcancelar = new javax.swing.JButton();
        ECcodigo = new javax.swing.JLabel();
        ECcedula = new javax.swing.JLabel();
        MEC = new javax.swing.JLabel();
        Ecodigo = new javax.swing.JTextField();
        Beliminar = new javax.swing.JButton();
        ECnombre = new javax.swing.JLabel();
        Ecedula = new javax.swing.JTextField();
        Enombre = new javax.swing.JTextField();
        ECdireccion = new javax.swing.JLabel();
        Edireccion = new javax.swing.JTextField();
        Etelefono = new javax.swing.JTextField();
        ECtelefono = new javax.swing.JLabel();
        Bbuscar = new javax.swing.JButton();
        Eapellido = new javax.swing.JTextField();
        ECapellido = new javax.swing.JLabel();

        Bcancelar.setText("CANCELAR");
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        ECcodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ECcodigo.setText("CODIGO");

        ECcedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ECcedula.setText("CEDULA");

        MEC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MEC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MEC.setText("ELIMINAR CLIENTE");

        Ecodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcodigoActionPerformed(evt);
            }
        });

        Beliminar.setText("ELIMINAR");
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });

        ECnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ECnombre.setText("NOMBRE");

        ECdireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ECdireccion.setText("DIRECCION");
        ECdireccion.setToolTipText("");

        ECtelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ECtelefono.setText("TELEFONO");

        Bbuscar.setText("BUSCAR");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        ECapellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ECapellido.setText("APELLIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ECcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ecodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ECnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ECcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ECapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Enombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ecedula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Eapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(MEC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Bbuscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Beliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bcancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ECdireccion)
                                .addComponent(ECtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Edireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Etelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(MEC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ecodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bbuscar))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ecedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECcedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECnombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECapellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ECdireccion)
                    .addComponent(Edireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ECtelefono)
                    .addComponent(Etelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bcancelar)
                    .addComponent(Beliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BcancelarActionPerformed

    private void EcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EcodigoActionPerformed

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(Ecodigo.getText());
        controladorCliente.delete(codigo);
        JOptionPane.showMessageDialog(this, "CLIENTE ELIMINADO");
        Ecodigo.setText("");
        Ecedula.setText("");
        Enombre.setText("");
        Eapellido.setText("");
        Edireccion.setText("");
        Etelefono.setText("");
    }//GEN-LAST:event_BeliminarActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(Ecodigo.getText());
        Cliente buscarCliente = controladorCliente.read(codigo);
        Ecedula.setText(buscarCliente.getCedula());
        Enombre.setText(buscarCliente.getNombre());
        Eapellido.setText(buscarCliente.getApellido());
        Edireccion.setText(buscarCliente.getDireccion());
        Etelefono.setText(buscarCliente.getTelefono());
    }//GEN-LAST:event_BbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Bbuscar;
    public static javax.swing.JButton Bcancelar;
    public static javax.swing.JButton Beliminar;
    public static javax.swing.JLabel ECapellido;
    public static javax.swing.JLabel ECcedula;
    public static javax.swing.JLabel ECcodigo;
    public static javax.swing.JLabel ECdireccion;
    public static javax.swing.JLabel ECnombre;
    public static javax.swing.JLabel ECtelefono;
    private javax.swing.JTextField Eapellido;
    private javax.swing.JTextField Ecedula;
    private javax.swing.JTextField Ecodigo;
    private javax.swing.JTextField Edireccion;
    private javax.swing.JTextField Enombre;
    private javax.swing.JTextField Etelefono;
    public static javax.swing.JLabel MEC;
    // End of variables declaration//GEN-END:variables
}
